#!/usr/bin/env bash
set -e

TESTING_DB="$POSTGRES_DB"_testing

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $TESTING_DB;
    GRANT ALL PRIVILEGES ON DATABASE $TESTING_DB TO $POSTGRES_USER;
EOSQL
