"""empty message

Revision ID: 7f74d2dc3988
Revises: d8fdcb44420e
Create Date: 2021-01-13 16:38:05.406975

"""
from alembic import op
import sqlalchemy as sa
import webapp


# revision identifiers, used by Alembic.
revision = '7f74d2dc3988'
down_revision = 'd8fdcb44420e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', webapp.type_decorators.Password(length=166), nullable=True),
    sa.Column('api_key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', webapp.type_decorators.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('processing', 'done', 'error', name='status'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('result_location', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('user')
    # ### end Alembic commands ###
